### ISSUE TITLE
Suggest fixes for env problems

### ISSUE THREAD

**Issue by schae234** [jackstanek/BotBot#25]
When you run the env checker, have suggestions for what went wrong.

e.g.
```
Report:
Environment variable problems:
PROB_VAR_NOT_SET: 'LD_LIBRARY_PATH'
```
Should suggest that `/panfs/roc/groups/3/mccuem/shared/.local/lib` should be in the LD_LIBRARY_PATH.

**Comment by jackstanek** [comment]
Should be fixed in 8a31047
