### ISSUE TITLE
Testing with Travis CI and py.test

### ISSUE THREAD

**Issue by schae234** [jackstanek/BotBot#3]
Since we are working on real data, we want to make sure that the code does what we expect it to do. We can easily to this with [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration) which is just a fancy way to run tests every time something is pushed to GitHub. [Travis CI](https://travis-ci.org/) provides a super easy service that integrates easily with Github, you basically just click a box and whenever you make a push or PR the test suite gets run.

While Travis runs the tests, we do need to actually write the tests. I've used a framework called py.test before, which works really nicely. Whenever we add some new functionality to the repo, we should test the outcomes with a [unit test](https://en.wikipedia.org/wiki/Unit_testing). Also, whenever we find a bug, we should fix it and write a [regression test](https://en.wikipedia.org/wiki/Regression_testing).

Tasks
------
- [x] Integrate botbot with travis-ci
- [x] Create a test directory with a stub for py.test
- [x] Read up on how py.test works 
- [x] Create a test for the `Checker` class

**Comment by jackstanek** [comment]
I think I have pretty good code coverage for the `Checker` class now.
