### ISSUE TITLE
Set up setup.py to make botbot installable

### ISSUE THREAD

**Issue by schae234** [jackstanek/BotBot#4]
The most common way to install a package is by using the setup.py command, it usually looks something like:
```
python setup.py install
```
The file itself if pretty simple and it also makes it easy to upload the package to [pypi](https://pypi.python.org/pypi) which allows us to install the package using [pip](https://pip.pypa.io/en/stable/). An example `setup.py` file is [here](https://github.com/schae234/Beer/blob/master/setup.py). 

Once the setup.py file is correctly written, you should be able to upload the package to pypi. 
This will also enable you to "test install" the package within your travis CI script. Research how the setup.py script should be formatted and implement one for botbot

Tasks
-------
- [x] Write a setup.py script
- [ ] Upload a version of the repo to pypi
- [ ] Add a installation line: e.g. `python setup.py install` to the .travis.yml file so we can test the installation process on Travis.

**Comment by schae234** [comment]
Additionally, there is a way to include scripts as executables within your `setup.py` so that after the package is installed, the script is accessible to be executed. For instance, you run `setup.py` and then a command called `botbot` will be available in the shell. There is a `scripts` directive within the setup function somewhere, add a `botbot` script or command there so that we can run the script from any directory once the package is installed.

- [ ] Add a scripts kwarg to the setup function to install an executable so we can run botbot from any directory within having to reference the script directly.

**Comment by jackstanek** [comment]
setup.py seems to work on my local machine. However, it looks like you already registered the name "BotBot" at PyPI, so PyPI won't let me upload under that name. Other than that, though, everything _should_ be fine, I think.

**Comment by schae234** [comment]
I think I might have taken the name back in the day. I'll look into
transferring it for you.

Ton

**Comment by schae234** [comment]
Hey @jackstanek 
What is your username on pypi?

Also, was botbot available instead? I think convention is that the pip package names are all lower case. If so, snag that name!

**Comment by jackstanek** [comment]
My username on PyPI is "jackstanek". I tried registering under botbot but apparently it automatically treats all names as lowercase internally, so it wouldn't let me take it.

**Comment by schae234** [comment]
Ok, should be updated. You should now be an "owner". Try it out!

**Comment by jackstanek** [comment]
Awesome! It looks like it works.
