### ISSUE TITLE
Add a checker that finds *.fastq files

### ISSUE THREAD

**Issue by schae234** [jackstanek/BotBot#5]
When we generate sequencing data, the raw file format we get back is in a `*.fastq` file. These files are **huge** because they are plain text files and they contain hundreds of millions of data points. Whenever something is sequenced, you have to pay a little bit of extra money to store the raw data, which is read only. Sometimes when people in the lab want to analyze the data, they mistakenly make a copy of the file in their analysis directory. This is bad because they are essentially copying tons of redundant information and wasting space for the sake of having a convenient path, they should have just used the `ln` command. 

As a first pass, lets just warn them when we find a `fastq` file as it is most likely a copy.

Tasks
-------
- [x] create checker function that warns the user when you come across a file named `*.fasq`

**Comment by jackstanek** [comment]
Implemented in commit 2fc5714. Haven't written a test for it yet

**Comment by schae234** [comment]
Lets keep it open till we have a test for it, so that we know that the implementation works. 
Things are looking really good though!!

**Comment by jackstanek** [comment]
The test for the *.fastq checker should be working correctly now. I'm finally getting used to Travis :)
