### ISSUE TITLE
botbot slow on MSI

### ISSUE THREAD

**Issue by schae234** [jackstanek/BotBot#9]
Not sure why!

**Comment by schae234** [comment]
Maybe following symlinks is causing cycles?
Maybe stat is calculating file size?

**Comment by jackstanek** [comment]
With verbosity turned off, I was able to get it to check the shared folder in 5 seconds. With verbosity on, it took 20 seconds. I'm guessing it might have something to do with ssh latency/overhead with regards to printing the output, but I think this is at least some improvement over what it was before.
